spring:
  datasource:
    #   数据源基本配置
    username: root
    password: 123456
    #   springboot2以上 com.mysql.jdbc.Driver已被弃用,改用com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://****:3306/tiktok?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#配置视频文件大小问题
  servlet:
    multipart:
      max-request-size: 1GB
      max-file-size: 200MB
# 配置redis
  redis:
    host:
    port: 6379
    password:

#springboot开启mybatis驼峰命名匹配映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true



